# Generated by Django 3.0.6 on 2020-05-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogengine', '0003_auto_20200513_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=40, unique=True),
        ),
    ]
